spring.application.name=demo
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/trading}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_MS:3600000}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.mvc.problemdetails.enabled=true
